[RockClimber.X2Ability_RockClimber]

; This mod creates multiple abilities, the "ability" granted to classes,
; the one granted by the item,
; the one granted by the vest
; and a passive one

; ==========================
; Ability : Class
; ==========================

;* Ability setup, TR_RockClimb_IsPassive_Ability = true, does nothing
; The Action Point cost of the ability, default is 1
TR_RockClimb_AP_Cost_Ability = 1

; The cooldown of the ability, default is 2
TR_RockClimb_Cooldown_Ability = 2

; The Number of turns the effect is active for, default is 3
TR_RockClimb_NumTurns_Ability = 3

; Does the ability has charges, default is false
TR_RockClimb_HasCharge_Ability = false

; The number of charges the ability has, default is 2
TR_RockClimb_InitialCharge_Ability = 2

; Is the ability free (AP cost), default is false
TR_RockClimb_IsFree_Ability = false

; Can the ability appear as an AWC perk, default is false
TR_RockClimb_IsCrossClass_Ability = false

; Is the ability passive, default is false
TR_RockClimb_IsPassive_Ability = false

; ==========================
; Ability : Item
; ==========================

;* Ability setup, TR_RockClimb_IsPassive_Item = true, does nothing
; The Action Point cost of the ability, default is 1
TR_RockClimb_AP_Cost_Item = 1

; The cooldown of the ability, default is 4
TR_RockClimb_Cooldown_Item = 4

; The Number of turns the effect is active for, default is 1
TR_RockClimb_NumTurns_Item = 1

; Is the item consumed after use, default is true
TR_RockClimb_Consume_Item = true

; Does the item has charges, default is true
TR_RockClimb_HasCharge_Item = true

; The number of charges the ability has, default is 2
TR_RockClimb_InitialCharge_Item = 2

; Is the ability free (AP cost), default is false
TR_RockClimb_IsFree_Item = false

; Is the ability passive, default is false
TR_RockClimb_IsPassive_Item = false

; ==========================
; Ability : Armour
; ==========================

;* Ability setup, TR_RockClimb_IsPassive_Item_Armour = true, does nothing
; The Action Point cost of the ability, default is 1
TR_RockClimb_AP_Cost_Item_Armour = 1

; The cooldown of the ability, default is 3
TR_RockClimb_Cooldown_Item_Armour = 3

; The Number of turns the effect is active for, default is 1
TR_RockClimb_NumTurns_Item_Armour = 1

; Does the item has charges, default is false
TR_RockClimb_HasCharge_Item_Armour = false

; The number of charges the ability has, default is 3
TR_RockClimb_InitialCharge_Item_Armour = 3

; Is the ability free (AP cost), default is false
TR_RockClimb_IsFree_Item_Armour = false

; Is the ability passive, default is true
TR_RockClimb_IsPassive_Item_Armour = true

; ==========================
; Ability : Vest
; ==========================

;* Ability setup, TR_RockClimb_IsPassive_Item_Vest = true, does nothing
; The Action Point cost of the ability, default is 1
TR_RockClimb_AP_Cost_Item_Vest = 1

; The cooldown of the ability, default is 5
TR_RockClimb_Cooldown_Item_Vest = 2

; The Number of turns the effect is active for, default is 3
TR_RockClimb_NumTurns_Item_Vest = 5

; Does the item has charges, default is false
TR_RockClimb_HasCharge_Item_Vest = false

; The number of charges the ability has, default is 3
TR_RockClimb_InitialCharge_Item_Vest = 3

; Is the ability free (AP cost), default is false
TR_RockClimb_IsFree_Item_Vest = true

; Is the ability passive, default is false
TR_RockClimb_IsPassive_Item_Vest = false

[RockClimber.X2Item_RockClimb]

; Is the item enabled (note, this doesn't disable the abilities), by default is True
IsRockClimbingEnabled_Item = true

; Build option for the item, by default it can't be build
TR_RockClimb_CanBeBuild_Item = false

; Is the item starting, by default it's starting
TR_RockClimb_IsStratingItem_Item = true

; Build option for the item, by default it's infinite
TR_RockClimb_IsInfinite_Item = true

; How much the item cost, if TR_RockClimb_IsInfinite_Item = true, does not apply
TR_RockClimb_TradeValue_Item = 5

; How much the item cost, if TR_RockClimb_IsInfinite_Item = true, does not apply
TR_RockClimb_Cost_Item = 20

; Enable or not the reversed image, by default is False
RockClimb_RevImage_Item = false

; =======================================================

; Is the vest enabled (note, this doesn't disable the abilities), by default is True
IsRockClimbingEnabled_Vest = true

; Build option for the vest, by default it can be build
TR_RockClimb_CanBeBuild_Vest = true

; Is the vest starting, by default it's not starting
TR_RockClimb_IsStratingItem_Vest = false

; Build option for the item, by default it's not infinite
TR_RockClimb_IsInfinite_Vest = false

; How much the item cost, if TR_RockClimb_IsInfinite_Vest = true, does not apply
TR_RockClimb_TradeValue_Vest = 10

; How much the item cost, if TR_RockClimb_IsInfinite_Vest = true, does not apply
TR_RockClimb_Cost_Vest = 30

; Enable or not the reversed image, by default is False
RockClimbing_RevImage_Vest = false

; The Health bonus of the vest, default is 2
TR_RockClimbing_HealthBonus_Vest = 2

; The Mobility bonus of the vest, default is 2
TR_RockClimbing_MobilityBonus_Vest = 2

[RockClimber.X2DLCInfo_RockClimber]

;* Adds the 'TR_RockClimb_Item' ability to the items listed
;+RockClimb_Items = 'BattleScanner'

;* Adds the 'TR_RockClimb_Item_Armour' ability to the armours listed
+RockClimb_Armours = 'LightPlatedArmor'
+RockClimb_Armours = 'LightPoweredArmor'
+RockClimb_Armours = 'LightAlienArmor'
+RockClimb_Armours = 'LightAlienArmorMk2'

;* Adds the 'TR_RockClimb_Ability_Passive' ability to the character groups listed
;+RockClimber_CharacterGroups = 'viper'

;* Adds the 'TR_RockClimb_Ability_Passive' ability to the unit names listed
;+RockClimber_UnitNames = 'AdvCaptainM3'

;* Adds the 'TR_RockClimb_Ability' ability to the classes listed
;+RockClimber_Classes = 'skirmisher'
