[RockClimber.X2Ability_RockClimber]

TR_RockClimb_AP_Cost_Ability = 1
TR_RockClimb_Cooldown_Ability = 2
TR_RockClimb_InitialCharge_Ability = 2
TR_RockClimb_NumCharge_Ability = 2
TR_RockClimb_IsFree_Ability = true
TR_RockClimb_IsCrossClass = false
TR_RockClimb_Ability_HasCharge = false
TR_RockClimb_NumTurns_Ability = 3
TR_RockClimb_IsPassive_Ability = false

TR_RockClimb_AP_Cost_Item = 1
TR_RockClimb_Cooldown_Item = 4
TR_RockClimb_InitialCharge_Item = 2
TR_RockClimb_NumCharge_Item = 2
TR_RockClimb_IsFree_Item = false
TR_RockClimb_ItemConsume = true
TR_RockClimb_NumTurns_Item = 1
TR_RockClimbItem_HasCharge = true
TR_RockClimb_IsPassive_Item = false

TR_RockClimb_AP_Cost_Item_Armour = 1
TR_RockClimb_Cooldown_Item_Armour = 3
TR_RockClimb_InitialCharge_Item_Armour = 3
TR_RockClimb_NumCharge_Item_Armour = 3
TR_RockClimb_IsFree_Item_Armour = false
TR_RockClimb_NumTurns_Item_Armour = 1
TR_RockClimb_Item_Armour_HasCharge = true
TR_RockClimb_IsPassive_Item_Armour = false

RockClimbingVest_HealthBonus = 3
RockClimbingVest_MobilityBonus = 2

[RockClimber.X2Item_RockClimb]

TR_RockClimb_CanBeBuild = true
TR_RockClimb_IsStratingItem = false
TR_RockClimb_IsInfinite = false
TR_RockClimb_TradeValue = 5
TR_RockClimb_Cost = 20

RockClimbItem_AltImage_Active = false

IsRockClimbingItemEnabled = true
IsRockClimbingVestEnabled = true

[RockClimber.X2DLCInfo_RockClimber]

;* Adds the 'TR_RockClimb_Item' ability
;+RockClimb_Items = ''

;* Adds the 'TR_RockClimb_Item_Armour' ability
+RockClimb_Armours = 'LightPlatedArmor'
+RockClimb_Armours = 'LightPoweredArmor'
+RockClimb_Armours = 'LightAlienArmor'
+RockClimb_Armours = 'LightAlienArmorMk2'

;* Adds the 'TR_RockClimb_AbilityPassive' ability
;+RockClimber_CharacterGroups = 'viper'

;* Adds the 'TR_RockClimb_AbilityPassive' ability
;+RockClimber_UnitName= 'AdvCaptainM3'

;* Adds the 'TR_RockClimb_Ability' ability
;+RockClimber_Classes = 'skirmisher'
