[RockClimber.X2Ability_RockClimber]

; This mod creates multiple abilities, the "ability" granted to classes,
; the one granted by the item,
; the one granted by the vest
; and a passive one

; ==========================
; Ability : Class
; ==========================

;* Ability setup, TR_RockClimb_IsPassive_Ability = true, does nothing
; The Action Point cost of the ability, default is 1
TR_RockClimb_AP_Cost_Ability = 1

; The cooldown of the ability, default is 2
TR_RockClimb_Cooldown_Ability = 2

; The Number of turns the effect is active for, default is 3
TR_RockClimb_NumTurns_Ability = 3

; Does the ability has charges, default is false
TR_RockClimb_HasCharge_Ability = false

; The number of charges the ability has, default is 2
TR_RockClimb_InitialCharge_Ability = 2

; Is the ability free (AP cost), default is false
TR_RockClimb_IsFree_Ability = false

; Can the ability appear as an AWC perk, default is false
TR_RockClimb_IsCrossClass_Ability = false

; Is the ability passive, default is false
TR_RockClimb_IsPassive_Ability = false

; ==========================
; Ability : Item
; ==========================

;* Ability setup, TR_RockClimb_IsPassive_Item = true, does nothing
; The Action Point cost of the ability, default is 1
TR_RockClimb_AP_Cost_Item = 1

; The cooldown of the ability, default is 4
TR_RockClimb_Cooldown_Item = 4

; The Number of turns the effect is active for, default is 1
TR_RockClimb_NumTurns_Item = 1

; Is the item consumed after use, default is true
TR_RockClimb_Consume_Item = true

; Does the item has charges, default is true
TR_RockClimb_HasCharge_Item = true

; The number of charges the ability has, default is 2
TR_RockClimb_InitialCharge_Item = 2

; Is the ability free (AP cost), default is false
TR_RockClimb_IsFree_Item = false

; Is the ability passive, default is false
TR_RockClimb_IsPassive_Item = false

; ==========================
; Ability : Armour
; ==========================

;* Ability setup, TR_RockClimb_IsPassive_Item_Armour = true, does nothing
; The Action Point cost of the ability, default is 1
TR_RockClimb_AP_Cost_Item_Armour = 1

; The cooldown of the ability, default is 3
TR_RockClimb_Cooldown_Item_Armour = 3

; The Number of turns the effect is active for, default is 1
TR_RockClimb_NumTurns_Item_Armour = 1

; Does the item has charges, default is false
TR_RockClimb_HasCharge_Item_Armour = false

; The number of charges the ability has, default is 3
TR_RockClimb_InitialCharge_Item_Armour = 3

; Is the ability free (AP cost), default is false
TR_RockClimb_IsFree_Item_Armour = false

; Is the ability passive, default is true
TR_RockClimb_IsPassive_Item_Armour = true

; ==========================
; Ability : Vest
; ==========================

;* Ability setup, TR_RockClimb_IsPassive_Item_Vest = true, does nothing
; The Action Point cost of the ability, default is 1
TR_RockClimb_AP_Cost_Item_Vest = 1

; The cooldown of the ability, default is 5
TR_RockClimb_Cooldown_Item_Vest = 2

; The Number of turns the effect is active for, default is 3
TR_RockClimb_NumTurns_Item_Vest = 5

; Does the item has charges, default is false
TR_RockClimb_HasCharge_Item_Vest = false

; The number of charges the ability has, default is 3
TR_RockClimb_InitialCharge_Item_Vest = 3

; Is the ability free (AP cost), default is false
TR_RockClimb_IsFree_Item_Vest = false

; Is the ability passive, default is false
TR_RockClimb_IsPassive_Item_Vest = false

[RockClimber.X2Item_RockClimb]

; The Health bonus of the vest, default is 2
TR_RockClimbing_HealthBonus_Vest = 2

; The Mobility bonus of the vest, default is 2
TR_RockClimbing_MobilityBonus_Vest = 2

[RockClimber.X2DLCInfo_RockClimber]

;* Enable logging for the mod, by default is false
; The logging is quite extensive, so it is recommended to only enable it when you need to debug something
; I mean it
bLog = false