[RockClimber.X2DLCInfo_RockClimber]
DLCIdentifier="RockClimber"

[RockClimber CHModDependency]
DisplayName="[WOTC] Rock Climber"


[RockClimber CHDLCRunOrder]
;+RunAfter=DLCIdentifier_A
;+RunBefore=DLCIdentifier_D

;RunPriorityGroup=RUN_FIRST
;RunPriorityGroup=RUN_STANDARD
;RunPriorityGroup=RUN_LAST
