[RockClimber.X2DLCInfo_RockClimber]
DLCIdentifier="RockClimber"

+RockClimb_Items=TR_RockClimb_Item

;* Add items here (cooldown, charges, 1AP cost)
; +RockClimb_Items=ItemTemplateNameHere

;* Armours that have a grappling hook
+RockClimb_Armours=LightPlatedArmor
+RockClimb_Armours=LightPoweredArmor
+RockClimb_Armours=LightAlienArmor
+RockClimb_Armours=LightAlienArmorMk2



[RockClimber CHModDependency]
DisplayName="[WOTC] Rock Climber"


[RockClimber CHDLCRunOrder]
;+RunAfter=DLCIdentifier_A
;+RunBefore=DLCIdentifier_D

;RunPriorityGroup=RUN_FIRST
;RunPriorityGroup=RUN_STANDARD
;RunPriorityGroup=RUN_LAST