[XComGame.X2SoldierClassTemplateManager]
;this only lifts the "a class must have the skill" condition. you still have to turn on crossclass in the XComGame.ini
+ExtraCrossClassAbilities=(AbilityName="TR_RockClimb_Ability")
