[RockClimber.X2DLCInfo_RockClimber]
DLCIdentifier="RockClimber"

[RockClimber CHModDependency]
DisplayName="RockClimber"

;+IncompatibleMods="DLCIdentifier_Of_Some_Mod_A"

;+RequiredMods="WOTCIridarTemplateMaster"

;+IgnoreRequiredMods="DLCIdentifier_Of_Some_Mod_F"


[RockClimber CHDLCRunOrder]
;+RunAfter=DLCIdentifier_A
;+RunBefore=DLCIdentifier_D

;RunPriorityGroup=RUN_FIRST
;RunPriorityGroup=RUN_STANDARD
;RunPriorityGroup=RUN_LAST